export const ADD_ITEM = 'ADD_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const SET_EDIT_ITEM = 'SET_EDIT_ITEM'
export const CANCEL_EDIT = 'CANCEL_EDIT'
export const CHANGE_FILTER = 'CHANGE_FILTER'